leanix:
  vsm:
    # Runtime settings
    mounted-volume: ${MOUNTED_VOLUME:}
    concurrency-factor: ${CONCURRENCY_FACTOR:3}

    # LeanIX configs
    leanix-host: ${LEANIX_HOST:}
    leanIx-token: ${LEANIX_TOKEN:}

    # Discovery API data
    source-type: ${SOURCE_TYPE:vsm-sbom-booster}
    source-instance: ${SOURCE_INSTANCE:}

    # GIT
    git-provider: ${GIT_PROVIDER:GITHUB}

    ## GITHUB
    github-api-host: ${GITHUB_API_HOST:api.github.com}
    github-token: ${GITHUB_TOKEN:}
    github-organization: ${GITHUB_ORGANIZATION:}

    ## GITLAB
    gitlab-api-host: ${GITLAB_API_HOST:gitlab.com}
    gitlab-token: ${GITLAB_TOKEN:}
    gitlab-group: ${GITLAB_GROUP:}
